/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DateRangePicker: typeof import('./components/DateRangePicker.vue')['default']
    DetailView: typeof import('./components/DetailView.vue')['default']
    FilterView: typeof import('./components/FilterView.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    ResponsiveTable: typeof import('./components/ResponsiveTable.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    TableView: typeof import('./components/TableView.vue')['default']
  }
}
