/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Barplot: typeof import('./components/Barplot.vue')['default']
    CountrySelect: typeof import('./components/CountrySelect.vue')['default']
    DetailView: typeof import('./components/DetailView.vue')['default']
    FilterView: typeof import('./components/FilterView.vue')['default']
    Lineplot: typeof import('./components/Lineplot.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    Scatterplot: typeof import('./components/Scatterplot.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    YearRange: typeof import('./components/YearRange.vue')['default']
  }
}
